# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV["CI"]
    api_key = app_store_connect_api_key(
      key_id: "RQC9XLTXM9",
      issuer_id: "69a6de7f-c90c-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./AuthKey_RQC9XLTXM9.p8",
      duration: 1200, # 20 minutes
      in_house: false # Set to true if you are using an in-house distribution certificate
    )
    increment_build_number(xcodeproj: "Guardian Quiz.xcodeproj")
    build_app(scheme: "Guardian Quiz")
    upload_to_testflight(api_key: api_key)
  end
end
